### ISSUE TITLE
Postgres database requires arbitrary role

### ISSUE THREAD

**Issue by alex-hancock** [BD2KGenomics/dcc-dashboard-service#12]
While user, password, and db location are all determined by environmental variables, the role name (in this case, "monitor") is hard-coded. We want to change this so that the YML docker-compose file can pass an arbitrary role name through an environmental variable so other components of dcc-ops can utilize that information.

**Comment by alex-hancock** [comment]
@caaespin 
Changed monitor.py, see latest commit in branch "feature/db-env"
PR after review on Friday?

**Comment by caaespin** [comment]
There was a typo in the name of the env var. Fixed that. It should all be good now.
