### ISSUE TITLE
File Browser: read from Elasticsearch and generate an API

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/dcc-dashboard-service#21]
File Browser: read from Elasticsearch and generate an API (facets and hits based on a config file)

**Comment by caaespin** [comment]
STATUS: Web Service reads from ElasticSearch and generates the main API (/repository/files). summary and keyword search api non-functional yet

**Comment by caaespin** [comment]
UPDATE: summary endpoint functional. export and keyword search non-functional still
