### ISSUE TITLE
File Browser: indexer creates index and puts it into Elasticsearch

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/dcc-dashboard-service#22]
File Browser: indexer creates index and puts it into Elasticsearch

**Comment by caaespin** [comment]
STATUS: The indexer creates and stores entries in an elasticsearch index based on a config file

**Comment by emikoifish** [comment]
STATUS: The indexer also scans the blue box daily and indexes items into Elasticsearch

**Comment by kozbo** [comment]
Please connect your Pull Requests to your issues by adding a comment in the PRs: "connected to #nn"

**Comment by caaespin** [comment]
UPDATE: Indexer creates the index and puts it into elasticsearch. Still needs work on the ElasticSearch mappings
