### ISSUE TITLE
File Browser: indexer picks up post notifications

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/dcc-dashboard-service#23]
File Browser: indexer picks up post notifications

**Comment by caaespin** [comment]
STATUS: Code picks up entries from simulated post requests. Still need to test with POST requests from an actual blue box

**Comment by kozbo** [comment]
Please connect your Pull Requests to your issues by adding a comment in the PRs: "connected to #nn"

**Comment by caaespin** [comment]
UPDATE: Indexer does pick up notifications from a Blue Box. Still need to work on mappings
