### ISSUE TITLE
Generate generic bagit

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/dcc-dashboard-service#54]
The lambda at DataBiosphere/bagit-firecloud-lambda expects the TSV currently generated by Boardwalk wrapped in a bagit. The lambda then splits the TSV in the bagit into two TSVs and POSTs them to FireCloud.

The lambda should be generic so consumers other than Boardwalk can use it. This means dcc-dashboard-service should do the logic to split apart the TSV and send a bagit with two TSV files to the lambda

**Comment by cricketsloan** [comment]
https://github.com/DataBiosphere/bagit-firecloud-lambda/commit/1001f0d44a833c8abb6e7046313d559f84a988c7
