### ISSUE TITLE
Fix TSV Generation for Export to FireCloud

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/dcc-dashboard-service#55]
1) The logic for generating the TSVs for FireCloud, which currently resides in a lambda, but should be moved into dcc-dashboard-service, assumes that there are always 2 rows per participant, one with a crai file, and one with a cram file.

2) There can be 1 to n rows per participant, and there can be many different file types.

**Comment by mjkrause** [comment]
1. working on the review - see https://github.com/DataBiosphere/bagit-firecloud-lambda/pull/4

**Comment by mjkrause** [comment]
creating new ticket of #2 above: There can be 1 to n rows per participant, and there can be many different file types.
