### ISSUE TITLE
Exp. to FC: creation of FC-compliant TSV needs to handle 1 to n filetypes

### ISSUE THREAD

**Issue by mjkrause** [BD2KGenomics/dcc-dashboard-service#61]
The user should be able to make as choice of filetype on Boardwalk, and the metadata TSV should upload into FireCloud.

For instance, there can be 1 to n rows per participant, and there can be many different file types (e.g., one or more filetypes can be associated with a donor UUID).

**Comment by coverbeck** [comment]
Reviewed and merged
